### ISSUE TITLE
eslint config in package.json vs local dotfile

### ISSUE THREAD

**Issue by offero** [oscarmorrison/react-webpack-starter#12]
This is probably not a bug and more of a lack of understanding of the tooling on my part. Why does eslint config live in package.json and not in a .eslintrc file?

**Comment by oscarmorrison** [comment]
`babel`, `eslint`, and `jest` can all have there own associated dotfile `.rc` \ `.json`. I have only kept in in the package.json as I was planning on keeping them as minimal as possible. I think the `eslint` has got a bit out of hand and could see argument for pulling it out. Also not sure how tools go about picking up the `eslint` in the `package.json` for editors.
